add_library(ct_core STATIC
    ${GAME_MODULE_DIR}/src/platform/raster.cpp ${GAME_MODULE_DIR}/src/platform/r3d.cpp ${GAME_MODULE_DIR}/src/platform/mesh.cpp
    ${GAME_MODULE_DIR}/src/level.cpp ${GAME_MODULE_DIR}/src/solver.cpp ${GAME_MODULE_DIR}/src/gen.cpp ${GAME_MODULE_DIR}/src/tiers.cpp ${GAME_MODULE_DIR}/src/levelset.cpp ${GAME_MODULE_DIR}/src/critters.cpp
    ${GAME_MODULE_DIR}/src/ground.cpp ${GAME_MODULE_DIR}/src/garden.cpp ${GAME_MODULE_DIR}/src/hedge.cpp ${GAME_MODULE_DIR}/src/field.cpp ${GAME_MODULE_DIR}/src/show.cpp ${GAME_MODULE_DIR}/src/lines.cpp ${GAME_MODULE_DIR}/src/save.cpp)
target_include_directories(ct_core PUBLIC "${GAME_MODULE_DIR}/src")
target_link_libraries(ct_core PUBLIC grass_core)  # the field round the garden (shared/grass)
target_link_libraries(ct_core PUBLIC soil_core)   # the beds and burrows (shared/soil)
target_compile_definitions(ct_core PRIVATE _USE_MATH_DEFINES)
if(MSVC)
    target_compile_options(ct_core PRIVATE /utf-8 /W4 /fp:precise)
else()
    target_compile_options(ct_core PRIVATE -Wall -Wextra -ffp-contract=off)
endif()
include(CTest)
add_executable(ct_rules_tests ${GAME_MODULE_DIR}/tests/thieves_tests.cpp)
target_link_libraries(ct_rules_tests PRIVATE ct_core)
add_test(NAME catchingthieves_rules COMMAND ct_rules_tests "${GAME_MODULE_DIR}/assets/levels/gardens.txt")
set_tests_properties(catchingthieves_rules PROPERTIES TIMEOUT 600)
add_executable(ct_contract_tests ${GAME_MODULE_DIR}/tests/core_contract_tests.cpp)
target_link_libraries(ct_contract_tests PRIVATE ct_core)
add_test(NAME catchingthieves_core_contract COMMAND ct_contract_tests)
add_executable(ct_preview ${GAME_MODULE_DIR}/tests/preview.cpp)
target_link_libraries(ct_preview PRIVATE ct_core)
add_executable(ct_levelgen ${GAME_MODULE_DIR}/tools/levelgen.cpp)
target_link_libraries(ct_levelgen PRIVATE ct_core)

if(GAMES_BUILD_APPLICATION)
    add_executable(catchingthieves_view_contract_tests "${GAME_MODULE_DIR}/tests/view_contract_tests.cpp")
    target_include_directories(catchingthieves_view_contract_tests PRIVATE "${PROJECT_SOURCE_DIR}/new-games/kit")
    target_link_libraries(catchingthieves_view_contract_tests PRIVATE vendor_game_ui)
    add_test(NAME catchingthieves_view_contract COMMAND catchingthieves_view_contract_tests)
    set_tests_properties(catchingthieves_view_contract PROPERTIES TIMEOUT 90 ENVIRONMENT "GAMES_ASSET_DIR=${GAMES_RUNTIME_ASSET_DIR}")
endif()
add_executable(ct_coon_motion_tests ${GAME_MODULE_DIR}/tests/coon_motion_tests.cpp)
target_link_libraries(ct_coon_motion_tests PRIVATE ct_core)
add_test(NAME catchingthieves_coon_motion COMMAND ct_coon_motion_tests)
