# The grass engine. Included once by the generated registry (and by a game's own
# standalone build) with ENGINE_DIR set to this folder.
if(TARGET grass_core)
  return()
endif()
find_package(Threads REQUIRED)
add_library(grass_core STATIC "${ENGINE_DIR}/src/lawn.cpp")
target_include_directories(grass_core PUBLIC "${ENGINE_DIR}/src")
target_compile_features(grass_core PUBLIC cxx_std_20)
target_link_libraries(grass_core PUBLIC Threads::Threads)
if(MSVC)
  target_compile_options(grass_core PRIVATE /utf-8 /W4 /fp:precise)
else()
  target_compile_options(grass_core PRIVATE -Wall -Wextra -ffp-contract=off)
endif()
include(CTest)
add_executable(grass_tests "${ENGINE_DIR}/tests/grass_tests.cpp")
target_link_libraries(grass_tests PRIVATE grass_core)
add_test(NAME grass_engine COMMAND grass_tests)
set_tests_properties(grass_engine PROPERTIES TIMEOUT 180)
