#!/usr/bin/env python3
"""Regenerate the game list in README.md from the games themselves.

    python3 tools/make_readme.py          rewrite README.md
    python3 tools/make_readme.py --check  exit 1 if README.md is out of date

Every folder games/<id>/ with a GAME.json is a game. Its entry is made of the
manifest's title and kind, its about.md (a short plain-text description) and its
screens/readme.jpg (or the screenshot GAME.json names under "readme_screenshot").
Games appear in shelf order (entry_id). Only the text between the two markers below
is generated; the rest of README.md is written by hand.
"""
from __future__ import annotations

import argparse
import html
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
START = "<!-- games:start (generated by tools/make_readme.py; edit games/<id>/about.md instead) -->"
END = "<!-- games:end -->"


def games() -> list[dict]:
    found = []
    for manifest_path in sorted((ROOT / "games").glob("*/GAME.json")):
        folder = manifest_path.parent
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        about_path = folder / "about.md"
        about = about_path.read_text(encoding="utf-8").strip() if about_path.is_file() else manifest["blurb"]
        shot = folder / manifest.get("readme_screenshot", "screens/readme.jpg")
        found.append({
            "entry": manifest["entry_id"],
            "id": manifest["id"],
            "title": manifest["title"],
            "kind": manifest["kind"],
            "about": " ".join(about.split()),
            "folder": folder.relative_to(ROOT).as_posix(),
            "shot": shot.relative_to(ROOT).as_posix() if shot.is_file() else None,
        })
    found.sort(key=lambda game: game["entry"])
    return found


def cell(game: dict) -> str:
    lines = ['<td width="50%" valign="top">']
    if game["shot"]:
        lines.append(f'<a href="{game["folder"]}"><img src="{game["shot"]}" alt="{html.escape(game["title"])}" width="100%"></a>')
    lines.append(f'<br><b><a href="{game["folder"]}">{html.escape(game["title"])}</a></b> · {html.escape(game["kind"])}')
    lines.append(f'<br>{html.escape(game["about"])}')
    lines.append("</td>")
    return "\n".join(lines)


def section(found: list[dict]) -> str:
    rows = []
    for index in range(0, len(found), 2):
        pair = found[index:index + 2]
        cells = [cell(game) for game in pair]
        if len(pair) == 1:
            cells.append('<td width="50%"></td>')
        rows.append("<tr>\n" + "\n".join(cells) + "\n</tr>")
    names = ", ".join(game["title"] for game in found[:-1]) + " and " + found[-1]["title"]
    return "\n".join([
        START,
        f"PlaySuite has **{len(found)} games**: {names}.",
        "",
        "<table>",
        *rows,
        "</table>",
        END,
    ])


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if README.md is out of date")
    args = parser.parse_args()
    text = README.read_text(encoding="utf-8")
    if START not in text or END not in text:
        print(f"README.md needs the markers {START!r} and {END!r}", file=sys.stderr)
        return 2
    before = text[: text.index(START)]
    after = text[text.index(END) + len(END):]
    updated = before + section(games()) + after
    if updated == text:
        return 0
    if args.check:
        print("README.md is out of date: run python3 tools/make_readme.py", file=sys.stderr)
        return 1
    README.write_text(updated, encoding="utf-8")
    print("README.md updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
