set(GAMES_RUNTIME_ASSET_DIR "" CACHE PATH "Complete verified portable runtime assets")
if(NOT EXISTS "${GAMES_RUNTIME_ASSET_DIR}/audio/portable_manifest.json")
    message(FATAL_ERROR "Prepare portable assets and set GAMES_RUNTIME_ASSET_DIR to their directory")
endif()
add_library(game_audio_adapters STATIC ${GAMES_MODULE_AUDIO}
    src/audio_loader.cpp src/pcm_player.cpp src/scene_audio.cpp src/fourpegs_audio.cpp src/audio.cpp)
target_include_directories(game_audio_adapters PUBLIC src)
target_link_libraries(game_audio_adapters PUBLIC GUIForms::Audio game_paths)
add_library(game_text_frames STATIC src/text_requests.cpp src/game_text.cpp)
target_include_directories(game_text_frames PUBLIC src)
target_link_libraries(game_text_frames PUBLIC GUIForms::TextMasks)
add_library(game_felt STATIC shared/felt/carpet.cpp shared/felt/image.cpp)
if(GAMES_MODULE_UI)
    add_library(vendor_game_ui STATIC ${GAMES_MODULE_UI})
    set(module_link_scope PUBLIC)
else()
    add_library(vendor_game_ui INTERFACE)
    set(module_link_scope INTERFACE)
endif()
target_link_libraries(vendor_game_ui ${module_link_scope} ${GAMES_MODULE_LIBRARIES}
    game_audio_adapters game_text_frames game_felt GUIForms::Application)
target_compile_definitions(vendor_game_ui INTERFACE _USE_MATH_DEFINES)
add_library(game_ui ${GAMES_MODULE_SOURCES} "${GAMES_CATALOG_DIR}/game_registry.cpp" shared/cards/table.cpp src/presentation.cpp shared/puzzles/puzzle_view.cpp src/collection.cpp src/open_link.cpp
    games/sudoku/src/sudoku_view.cpp src/suite.cpp src/text_sprites.cpp src/shelf.cpp src/capsule.cpp shared/puzzles/kitten.cpp
    src/help_book.cpp src/help_content.cpp src/settings_sheet.cpp src/suite_model.cpp)
target_include_directories(game_ui PUBLIC src PRIVATE shared/felt)
target_link_libraries(game_ui PUBLIC game_rules game_solver game_raster sudoku_generator vendor_game_ui)
if(WIN32)
    target_link_libraries(game_ui PRIVATE shell32)
endif()
if(NOT MSVC)
    target_compile_options(game_ui PRIVATE -Wall -Wextra)
endif()
add_executable(games MACOSX_BUNDLE src/main.cpp src/dogfood.cpp)
if(WIN32)
    set_target_properties(games PROPERTIES WIN32_EXECUTABLE TRUE)
    if(MSVC)
        target_link_options(games PRIVATE /ENTRY:mainCRTStartup)
    endif()
endif()
target_link_libraries(games PRIVATE game_ui)
set_target_properties(games PROPERTIES
    MACOSX_BUNDLE_BUNDLE_NAME "PlaySuite"
    MACOSX_BUNDLE_GUI_IDENTIFIER "org.rainstar.games"
    MACOSX_BUNDLE_BUNDLE_VERSION "${PROJECT_VERSION}"
    MACOSX_BUNDLE_SHORT_VERSION_STRING "${PROJECT_VERSION}")
if(APPLE)
    set(games_resources "$<TARGET_BUNDLE_DIR:games>/Contents/Resources")
    set(games_libraries "$<TARGET_BUNDLE_DIR:games>/Contents/Frameworks")
    set_target_properties(games PROPERTIES BUILD_RPATH "@executable_path/../Frameworks")
    set_source_files_properties(assets/Games.icns PROPERTIES MACOSX_PACKAGE_LOCATION "Resources")
    target_sources(games PRIVATE assets/Games.icns)
    set_target_properties(games PROPERTIES MACOSX_BUNDLE_ICON_FILE "Games.icns")
else()
    set(games_resources "$<TARGET_FILE_DIR:games>")
    set(games_libraries "$<TARGET_FILE_DIR:games>")
    if(UNIX)
        set_target_properties(games PROPERTIES BUILD_RPATH "$ORIGIN")
    endif()
endif()
add_custom_command(TARGET games POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E make_directory "${games_libraries}"
    COMMAND ${CMAKE_COMMAND} -E copy_if_different "$<TARGET_FILE:GUIForms::Application>" "${games_libraries}"
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${GAMES_RUNTIME_ASSET_DIR}" "${games_resources}/assets"
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${GUIForms_FONT_DIR}" "${games_resources}/fonts"
    VERBATIM)
if(UNIX)
    add_custom_command(TARGET games POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "$<TARGET_FILE:GUIForms::Application>"
            "${games_libraries}/$<TARGET_SONAME_FILE_NAME:GUIForms::Application>"
        VERBATIM)
endif()
add_executable(ui_tests tests/ui_tests.cpp)
add_executable(puzzle_frame_tests tests/puzzle_frame_tests.cpp)
if("gems" IN_LIST GAMES_MODULE_IDS AND "untangle" IN_LIST GAMES_MODULE_IDS)
add_executable(puzzle_native_framebuffer_tests MACOSX_BUNDLE tests/puzzle_native_framebuffer_tests.cpp)
target_link_libraries(puzzle_native_framebuffer_tests PRIVATE game_ui)
if(APPLE)
    set(framebuffer_test_resources "$<TARGET_BUNDLE_DIR:puzzle_native_framebuffer_tests>/Contents/Resources")
else()
    set(framebuffer_test_resources "$<TARGET_FILE_DIR:puzzle_native_framebuffer_tests>")
endif()
add_custom_command(TARGET puzzle_native_framebuffer_tests POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${GUIForms_FONT_DIR}" "${framebuffer_test_resources}/fonts")
if(UNIX AND NOT APPLE)
    find_program(GAMES_XVFB_RUN xvfb-run)
endif()
if(GAMES_XVFB_RUN)
    add_test(NAME puzzle_native_framebuffers COMMAND ${GAMES_XVFB_RUN} -a $<TARGET_FILE:puzzle_native_framebuffer_tests>)
else()
    add_test(NAME puzzle_native_framebuffers COMMAND $<TARGET_FILE:puzzle_native_framebuffer_tests>)
endif()
set_tests_properties(puzzle_native_framebuffers PROPERTIES TIMEOUT 120 ENVIRONMENT "GAMES_ASSET_DIR=${GAMES_RUNTIME_ASSET_DIR}")
endif()
target_link_libraries(puzzle_frame_tests PRIVATE game_ui)
add_test(NAME puzzle_frames COMMAND puzzle_frame_tests)
set_tests_properties(puzzle_frames PROPERTIES ENVIRONMENT "GAMES_ASSET_DIR=${GAMES_RUNTIME_ASSET_DIR}")
if("fourpegs" IN_LIST GAMES_MODULE_IDS)
add_executable(fourpegs_pointer_tests tests/fourpegs_pointer_tests.cpp)
target_link_libraries(fourpegs_pointer_tests PRIVATE vendor_game_ui)
add_test(NAME fourpegs_pointer COMMAND fourpegs_pointer_tests)
set_tests_properties(fourpegs_pointer PROPERTIES ENVIRONMENT "GAMES_ASSET_DIR=${GAMES_RUNTIME_ASSET_DIR}")
endif()
target_link_libraries(ui_tests PRIVATE game_ui)
add_test(NAME ui_routing COMMAND ui_tests)
set(collection_fixture_available TRUE)
foreach(required solitaire spider freecell hearts sudoku gems cube untangle atomprobe fourpegs switchbox solve eggy koikoi parrots liarsdice penthesheep zenconstruction)
    if(NOT required IN_LIST GAMES_MODULE_IDS)
        set(collection_fixture_available FALSE)
    endif()
endforeach()
if(collection_fixture_available)
add_executable(collection_ui_tests tests/collection_ui_tests.cpp)
target_link_libraries(collection_ui_tests PRIVATE game_ui)
add_test(NAME collection_ui COMMAND collection_ui_tests)
set_tests_properties(collection_ui PROPERTIES
    ENVIRONMENT "GAMES_ASSET_DIR=${GAMES_RUNTIME_ASSET_DIR}")
endif()
set_tests_properties(ui_routing PROPERTIES ENVIRONMENT "GAMES_ASSET_DIR=${GAMES_RUNTIME_ASSET_DIR}")
add_executable(audio_tests tests/audio_tests.cpp)
target_link_libraries(audio_tests PRIVATE GUIForms::Audio)
add_test(NAME audio COMMAND audio_tests "${GAMES_RUNTIME_ASSET_DIR}" ogg)
add_executable(audio_policy_tests tests/audio_policy_tests.cpp)
target_link_libraries(audio_policy_tests PRIVATE game_audio_adapters)
add_test(NAME audio_policy COMMAND audio_policy_tests)
if("fourpegs" IN_LIST GAMES_MODULE_IDS)
add_executable(fourpegs_audio_tests tests/fourpegs_audio_tests.cpp)
target_link_libraries(fourpegs_audio_tests PRIVATE game_audio_adapters)
add_test(NAME fourpegs_bar_audio COMMAND fourpegs_audio_tests "${GAMES_RUNTIME_ASSET_DIR}")
endif()
add_executable(vendor_game_frame_tests tests/vendor_game_frame_tests.cpp)
foreach(game IN LISTS GAMES_NATIVE_FRAME_MODULES)
    target_compile_definitions(vendor_game_frame_tests PRIVATE GAMES_FRAME_${game})
endforeach()
target_link_libraries(vendor_game_frame_tests PRIVATE vendor_game_ui)
foreach(game IN LISTS GAMES_NATIVE_FRAME_MODULES)
    add_test(NAME ${game}_native_frames COMMAND vendor_game_frame_tests "${GAMES_RUNTIME_ASSET_DIR}" ${game})
    set_tests_properties(${game}_native_frames PROPERTIES TIMEOUT 45)
endforeach()
add_executable(raster_bench tools/raster_bench.cpp)
target_link_libraries(raster_bench PRIVATE game_ui)

add_executable(shelf_help_tests tests/shelf_help_tests.cpp)
target_link_libraries(shelf_help_tests PRIVATE game_ui)
add_test(NAME shelf_help COMMAND shelf_help_tests)
set_tests_properties(shelf_help PROPERTIES ENVIRONMENT "GAMES_ASSET_DIR=${GAMES_RUNTIME_ASSET_DIR}")
add_executable(catalog_ui_tests tests/catalog_ui_tests.cpp)
target_link_libraries(catalog_ui_tests PRIVATE game_ui)
add_test(NAME catalog_ui COMMAND catalog_ui_tests)
set_tests_properties(catalog_ui PROPERTIES TIMEOUT 180 ENVIRONMENT "GAMES_ASSET_DIR=${GAMES_RUNTIME_ASSET_DIR}")
