# A per-game portable core build. Graphical play uses the shared PlaySuite host.
get_filename_component(PLAYSUITE_SOURCE_DIR "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(GAME_MODULE_DIR "${CMAKE_CURRENT_SOURCE_DIR}")
get_filename_component(GAME_MODULE_ID "${GAME_MODULE_DIR}" NAME)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
if(NOT CMAKE_BUILD_TYPE)
  set(CMAKE_BUILD_TYPE Release CACHE STRING "Build type" FORCE)
endif()
if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
  set(CMAKE_POSITION_INDEPENDENT_CODE ON)
endif()
enable_testing()
find_package(Threads REQUIRED)
set(GAMES_BUILD_APPLICATION OFF)
add_library(game_paths "${PLAYSUITE_SOURCE_DIR}/src/runtime_paths.cpp")
target_include_directories(game_paths PUBLIC "${PLAYSUITE_SOURCE_DIR}/src")

# These modules share the established card/puzzle rules and their acceptance suite.
if(DEFINED GAME_SHARED_ENGINE)
  add_library(game_rules
    "${PLAYSUITE_SOURCE_DIR}/src/game.cpp"
    "${PLAYSUITE_SOURCE_DIR}/src/storage.cpp"
    "${PLAYSUITE_SOURCE_DIR}/src/scores.cpp"
    "${PLAYSUITE_SOURCE_DIR}/src/sudoku.cpp"
    "${PLAYSUITE_SOURCE_DIR}/src/puzzles.cpp")
  target_include_directories(game_rules PUBLIC "${PLAYSUITE_SOURCE_DIR}/src")
  target_link_libraries(game_rules PUBLIC game_paths)
  add_executable(rules_tests "${PLAYSUITE_SOURCE_DIR}/tests/rules_tests.cpp")
  target_link_libraries(rules_tests PRIVATE game_rules)
  add_test(NAME rules COMMAND rules_tests)
  add_executable(storage_tests "${PLAYSUITE_SOURCE_DIR}/tests/storage_tests.cpp")
  target_link_libraries(storage_tests PRIVATE game_rules)
  add_test(NAME storage COMMAND storage_tests)
  if(GAME_SHARED_ENGINE STREQUAL "cards")
    add_library(game_solver "${PLAYSUITE_SOURCE_DIR}/src/solitaire_solver.cpp" "${PLAYSUITE_SOURCE_DIR}/src/deal_tables.cpp")
    target_link_libraries(game_solver PUBLIC game_rules)
    add_executable(solver_tests "${PLAYSUITE_SOURCE_DIR}/tests/solver_tests.cpp")
    target_link_libraries(solver_tests PRIVATE game_solver)
    add_test(NAME solver COMMAND solver_tests)
  elseif(GAME_SHARED_ENGINE STREQUAL "sudoku")
    include(FetchContent)
    FetchContent_Declare(quickjs
      GIT_REPOSITORY https://github.com/quickjs-ng/quickjs.git
      GIT_TAG 8eb27e39848b73885e092777f0a67a4a2d8e5b99)
    set(QJS_ENABLE_INSTALL OFF CACHE BOOL "" FORCE)
    set(QJS_BUILD_LIBC OFF CACHE BOOL "" FORCE)
    FetchContent_MakeAvailable(quickjs)
    set_property(DIRECTORY "${quickjs_SOURCE_DIR}" PROPERTY EXCLUDE_FROM_ALL TRUE)
    add_library(sudoku_generator "${PLAYSUITE_SOURCE_DIR}/src/sudoku_bridge.cpp")
    target_link_libraries(sudoku_generator PUBLIC game_rules PRIVATE qjs)
    add_executable(sudoku_tests "${PLAYSUITE_SOURCE_DIR}/tests/sudoku_tests.cpp")
    target_link_libraries(sudoku_tests PRIVATE sudoku_generator)
    target_compile_definitions(sudoku_tests PRIVATE GAMES_TEST_ASSET_DIR="${PLAYSUITE_SOURCE_DIR}/assets")
    add_test(NAME sudoku COMMAND sudoku_tests)
  else()
    add_library(game_raster "${PLAYSUITE_SOURCE_DIR}/src/puzzle_render.cpp" "${PLAYSUITE_SOURCE_DIR}/src/puzzle_image.cpp")
    target_link_libraries(game_raster PUBLIC game_rules)
    add_executable(raster_tests "${PLAYSUITE_SOURCE_DIR}/tests/raster_tests.cpp")
    target_link_libraries(raster_tests PRIVATE game_raster)
    add_test(NAME raster COMMAND raster_tests)
    add_executable(puzzle_tests "${PLAYSUITE_SOURCE_DIR}/tests/puzzle_tests.cpp")
    target_link_libraries(puzzle_tests PRIVATE game_rules)
    add_test(NAME puzzles COMMAND puzzle_tests)
  endif()
endif()
# Shared engines the game names in GAME.json ("engines"), built before the game.
file(READ "${GAME_MODULE_DIR}/GAME.json" game_manifest)
string(JSON game_engine_count ERROR_VARIABLE game_engine_error LENGTH "${game_manifest}" engines)
if(NOT game_engine_error AND game_engine_count GREATER 0)
  math(EXPR game_engine_last "${game_engine_count} - 1")
  foreach(game_engine_index RANGE ${game_engine_last})
    string(JSON game_engine GET "${game_manifest}" engines ${game_engine_index})
    if(NOT game_engine MATCHES "^[a-z][a-z0-9_]*$" OR NOT EXISTS "${PLAYSUITE_SOURCE_DIR}/engines/${game_engine}/build.cmake")
      message(FATAL_ERROR "${GAME_MODULE_ID} names an unknown engine '${game_engine}'")
    endif()
    set(ENGINE_DIR "${PLAYSUITE_SOURCE_DIR}/engines/${game_engine}")
    include("${ENGINE_DIR}/build.cmake")
  endforeach()
endif()
include("${GAME_MODULE_DIR}/build.cmake")

# Release builds must still execute assertion-based acceptance checks.
get_property(game_targets DIRECTORY PROPERTY BUILDSYSTEM_TARGETS)
foreach(game_target IN LISTS game_targets)
  if(game_target MATCHES "_tests$")
    if(MSVC)
      target_compile_options(${game_target} PRIVATE /UNDEBUG)
    else()
      target_compile_options(${game_target} PRIVATE -UNDEBUG)
    endif()
  endif()
endforeach()
